### ISSUE TITLE
User sign up returns Internal server error 500

### ISSUE THREAD

**Issue by alexkayabula** [blakes24/dive-atlas#10]
## How to replicate the bug locally
- Start the application
- Access `http://127.0.0.1:5000/signup` from the browser
- Supply valid username, email, and password
- Submit

![Screen Shot 2020-12-12 at 11 28 27 AM](https://user-images.githubusercontent.com/31479458/101979323-35fff200-3c6d-11eb-8389-335d720f963c.png)

**Comment by blakes24** [comment]
I can't reproduce the error. What branch were you on?

**Comment by alexkayabula** [comment]
I was on the `login` branch.

**Comment by blakes24** [comment]
I added a seed file to the login branch. Try running that first to see if it fixes the error.

**Comment by alexkayabula** [comment]
Let me test it out.
