### ISSUE TITLE
Coverage badge not displaying test coverage

### ISSUE THREAD

**Issue by alexkayabula** [blakes24/dive-atlas#8]
I am of the view that the coverage badge should be able to display the test coverage.

**Comment by blakes24** [comment]
I've been trying to get it to work but I can't figure it out. At first, travis wasn't sending the reports to coveralls and my coveralls page said no builds yet, but now that it is my coveralls page just shows a blank %. 
<img width="655" alt="coveralls" src="https://user-images.githubusercontent.com/62186905/101977890-be4aac80-3c05-11eb-937a-dc6ed388760f.png">

**Comment by alexkayabula** [comment]
Create a pull request for the fix so that we can follow up.

**Comment by alexkayabula** [comment]
Thanx @blakes24.
